"""Render installer-owned OpenCode runtime settings.

The installer deliberately does not edit ``opencode.json`` or ``opencode.jsonc``.
OpenCode auto-loads the small local plugin emitted here, and that plugin merges
the transaction-owned runtime settings into the mutable resolved config.
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Iterable

from . import Entry, StateError

RUNTIME_PATH = "awesome-agency/runtime.json"
RUNTIME_AGENCY_PATH = "awesome-agency/runtime/agency.js"
RUNTIME_VAULT_PATH = "awesome-agency/runtime/vault.js"
PLUGIN_PATH = "plugins/awesome-agency.js"
SDD_SOURCE_TO_TARGET = {
    "sdd/skills/subagent-model-policy/SKILL.md": "skills/subagent-model-policy/SKILL.md",
    "sdd/agents/sdd-worker.md": "agents/sdd-worker.md",
    "sdd/agents/sdd-reviewer.md": "agents/sdd-reviewer.md",
    "sdd/plugins/subagent-dispatch.ts": "awesome-agency/runtime/subagent-dispatch.ts",
}
_ENV = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
_PROJECT = re.compile(r"\$\{CLAUDE_PROJECT_DIR(?::-[^}]*)?\}")

_PLUGIN = r'''// Generated by awesome-agency. Do not edit; it is transaction-owned.
// Compose runtime config/lifecycle hooks with the model-aware dispatcher.
import { AwesomeAgency } from '../awesome-agency/runtime/agency.js'
import SubagentDispatch from '../awesome-agency/runtime/subagent-dispatch.ts'

export default async function (context) {
  const runtime = await AwesomeAgency(context)
  const dispatch = await SubagentDispatch(context)
  return { ...runtime, tool: { ...runtime.tool, ...dispatch.tool } }
}
'''


def _entry_fields(entry: Entry | dict) -> tuple[str, str, Path, dict]:
    if isinstance(entry, Entry):
        return entry.name, entry.kind, Path(entry.source), entry.manifest
    return str(entry["name"]), str(entry.get("kind", "bundle")), Path(entry["source"]), dict(entry.get("manifest", entry))


def _strip_jsonc(text: str) -> str:
    """Remove JSONC comments while respecting quoted strings."""
    out: list[str] = []
    in_string = False
    escaped = False
    i = 0
    while i < len(text):
        char = text[i]
        if in_string:
            out.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            i += 1
            continue
        if char == '"':
            in_string = True
            out.append(char)
            i += 1
        elif text.startswith("//", i):
            i = text.find("\n", i)
            if i < 0:
                break
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            if end < 0:
                raise StateError("unterminated JSONC comment")
            i = end + 2
        else:
            out.append(char)
            i += 1
    return "".join(out)


def _load_user_config(path: Path) -> dict:
    try:
        text = path.read_text(encoding="utf-8")
        text = re.sub(r",\s*([}\]])", r"\1", _strip_jsonc(text))
        value = json.loads(text)
    except (OSError, json.JSONDecodeError) as error:
        raise StateError(f"cannot inspect OpenCode config {path}: {error}") from error
    if not isinstance(value, dict):
        raise StateError(f"OpenCode config must contain an object: {path}")
    return value


def _user_configs(target: Path, project: Path | None) -> list[tuple[Path, dict]]:
    if project is not None:
        xdg = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
        global_candidates = [xdg / "opencode" / "opencode.json", xdg / "opencode" / "opencode.jsonc"]
        project_candidates = [project / "opencode.json", project / "opencode.jsonc", project / ".opencode" / "opencode.json"]
    else:
        global_candidates = [target / "opencode.json", target / "opencode.jsonc"]
        project_candidates = []
    groups = [global_candidates, project_candidates]
    existing: list[Path] = []
    for group in groups:
        present = [path for path in group if path.exists()]
        if len(present) > 1:
            raise StateError("competing OpenCode config locations: " + ", ".join(str(path) for path in present))
        existing.extend(present)
    return [(path, _load_user_config(path)) for path in existing]


def _package_root(kind: str, name: str, source: Path | None = None) -> str:
    identity = name
    if source is not None:
        identity = source.stem if kind == "agent" and source.is_file() else source.name
    directory = {"bundle": "bundles", "agent": "agents", "skill": "skills", "command": "commands"}.get(kind, kind)
    return f"awesome-agency/packages/{directory}/{identity}"


def _replace_placeholders(value: object, package_root: str) -> object:
    if isinstance(value, list):
        return [_replace_placeholders(item, package_root) for item in value]
    if isinstance(value, dict):
        return {key: _replace_placeholders(item, package_root) for key, item in value.items()}
    if not isinstance(value, str):
        return value
    value = _PROJECT.sub("{project}", value)
    value = value.replace("${CLAUDE_PLUGIN_ROOT}", "{package_root:" + package_root + "}")
    value = _ENV.sub(lambda match: "{env:" + match.group(1) + "}", value)
    return value


def _mcp_from_entry(name: str, kind: str, source: Path) -> dict:
    fragment = source / "opencode" / "opencode.json"
    if not fragment.is_file():
        fragment = source / ".mcp.json"
    if not fragment.is_file():
        return {}
    try:
        data = json.loads(fragment.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise StateError(f"cannot read MCP fragment {fragment}: {error}") from error
    raw = data.get("mcp", {}) if fragment.name == "opencode.json" else data.get("mcpServers", {})
    if not isinstance(raw, dict):
        raise StateError(f"MCP fragment must contain an object: {fragment}")
    package_root = _package_root(kind, name, source)
    result: dict = {}
    for server_name, server in raw.items():
        if not isinstance(server, dict):
            raise StateError(f"MCP server {server_name} in {fragment} must be an object")
        converted = dict(server)
        if fragment.name == ".mcp.json":
            if converted.get("type") == "stdio":
                converted["type"] = "local"
            elif "command" in converted and "type" not in converted:
                converted["type"] = "local"
            if "command" in converted and isinstance(converted["command"], str):
                converted["command"] = [converted["command"]] + list(converted.pop("args", []))
            elif "args" in converted:
                converted["command"] = list(converted.pop("args"))
            if "env" in converted:
                converted["environment"] = converted.pop("env")
        result[server_name] = _replace_placeholders(converted, package_root)
    return result


def render_configuration(entries: Iterable[Entry | dict], target: Path, project: Path | None) -> dict[str, bytes]:
    """Return transaction-owned runtime settings and auto-discovered plugin bytes."""
    target = Path(target)
    entries = list(entries)
    user_configs = _user_configs(target, project)
    user_mcp: dict = {}
    for path, config in user_configs:
        mcp = config.get("mcp", {})
        if mcp is None or not isinstance(mcp, dict):
            raise StateError(f"OpenCode config field 'mcp' must be an object: {path}")
        user_mcp.update(mcp)

    runtime_entries = []
    mcp: dict = {}
    for entry in entries:
        name, kind, source, _manifest = _entry_fields(entry)
        contribution = _mcp_from_entry(name, kind, source)
        runtime_entries.append({
            "name": name,
            "kind": kind,
            "version": entry.version if isinstance(entry, Entry) else str(entry.get("version", "")),
            "source": str(source.resolve()),
            "package_root": _package_root(kind, name, source),
            "contribution": {"mcp": contribution},
        })
        for server_name, server in contribution.items():
            if server_name in mcp and mcp[server_name] != server:
                raise StateError(f"selected entries disagree on mcp.{server_name}")
            mcp[server_name] = server

    for server_name in list(mcp):
        if server_name in user_mcp:
            del mcp[server_name]

    runtime = {
        "version": 1,
        "project_context": "project" if project is not None else "runtime",
        "entries": runtime_entries,
        "mcp": mcp,
    }
    runtime_dir = Path(__file__).resolve().parents[1] / "runtime"
    try:
        agency = (runtime_dir / "agency.js").read_bytes()
        vault = (runtime_dir / "vault.js").read_bytes()
    except OSError as error:
        raise StateError(f"cannot read managed runtime helpers: {runtime_dir}: {error}") from error
    rendered = {
        RUNTIME_PATH: (json.dumps(runtime, indent=2, sort_keys=True) + "\n").encode("utf-8"),
        RUNTIME_AGENCY_PATH: agency,
        RUNTIME_VAULT_PATH: vault,
        PLUGIN_PATH: _PLUGIN.encode("utf-8"),
    }
    if entries:
        source_root = Path(__file__).resolve().parents[1]
        try:
            rendered.update({
                target_path: (source_root / source_path).read_bytes()
                for source_path, target_path in SDD_SOURCE_TO_TARGET.items()
            })
        except OSError as error:
            raise StateError(f"cannot read automatic SDD sources: {source_root / 'sdd'}: {error}") from error
    return rendered
